### ISSUE TITLE
Can you explain this paragraph?

### ISSUE THREAD

**Issue by huynq55-v2** [krukah/robopoker#24]
> Ultimately, we are brute forcing this step by iterating over the entire space of 3.1B distinguishable game states, which requires enumerating all 3T possible NLHE showdowns. An impending optimization will be to reduce the space of Observation by enforcing strategic isomorphism. Even at this first preprocessing step, scale becomes a massive bottleneck.

Can you explain the number 3.1B and 3T?

3T = 3B * 1326?

Have you seen this repo? I think it may be useful.

https://github.com/kdub0/hand-isomorphism

**Comment by huynq55-v2** [comment]
https://github.com/kdub0/hand-isomorphism/blob/master/src/check-main.c

  assert(hand_indexer_size(&preflop_indexer, 0) == 169);
  assert(hand_indexer_size(&flop_indexer, 0) == 169);
  assert(hand_indexer_size(&turn_indexer, 0) == 169);
  assert(hand_indexer_size(&river_indexer, 0) == 169);
  assert(hand_indexer_size(&flop_indexer, 1) == 1286792);
  assert(hand_indexer_size(&turn_indexer, 1) == 1286792);
  assert(hand_indexer_size(&river_indexer, 1) == 1286792);
  assert(hand_indexer_size(&turn_indexer, 2) == 55190538);
  assert(hand_indexer_size(&river_indexer, 2) == 55190538);
  assert(hand_indexer_size(&river_indexer, 3) == 2428287420);

In preflop there are 169 unique 2 cards. In the last round, there are 2428287420 unique 7 cards.

I believe that the 2,428,287,420 distinct combinations already include distinctions based on which rounds the cards are in.

For example: (As Ah) (2s 3s 4s) (5s) (6c) is different from (As Ah) (2s 3s 6c) (4s) (5s).

**Comment by huynq55-v2** [comment]
To use less RAM, for example my laptop only has 32GB RAM, can we pre compute River equities and save results to disk?

There will be about 3.1B lines of result right? Use zip to zip these files

Then we can run k mean cluster using these files. I think it will not require much RAM or disk.

What do you think?

**Comment by krukah** [comment]
hey, thanks for opening the issue -- so the README is actually quite outdated, and some relevant changes since its last update:
- i read the Waugh et al paper and specifically liked the colexicographical ordering principle. but i really didn't love the accompanying C implementation. i found it quite unreadable and thought it would be easier to just write myself, in line with Rust idiomatics + robopoker data structures. 
- there are `Permutation` and `Isomorphism` structures now that encapsulate exactly this. again, most of the metrics in the README are quite outdated, and now running a full deck should only require <10GB RAM
- we could indeed save all isomorphic River equities to disk. in fact, this was implemented in a previous version (albeit suboptimally). the key would be to come up with a unifying trait that allows for loading and writing to disk in a pgcopy compatible way. this is something i'm working on currently, and you can see the foundations for it in the `::save()` methods on `Encoder, Profile, Layer, Metric`
- however, running kmeans is the bottleneck, not generating/storing abstractions. so even if we exhaustively precompute equities of RiverIsomorphism, we'd still be bottlenecked by the `O(N * K^2 )` runtime of clustering kmeans. but learning the encoding/abstraction is one-time cost that can and should be persisted to disk. again, currently working on making this as clean as possible, and also keeping it Postgres compatible
- most of the "magic numbers" are defined in `street.rs`. useful for back-of-envelope time & size calculations
- we have a `shortdeck` feature implemented, which is great for iterating and running locally if you are CPU or RAM bound. courtesy of @reinismu

**Comment by krukah** [comment]
i'm working w 16GB on my machine so trust me, memory efficiency is always at top of mind :)

**Comment by huynq55-v2** [comment]
Thank you for clarifying the issue. There's nothing better than a clearly explained code base. I'll close this issue now.
